name: Plugin Release Archive
on:
  release:
    types: [published]
jobs:
  pack-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: SPSauce
        run: ./sps release.sauce --GITHUB_TOKEN ${{secrets.GITHUB_TOKEN}}