name: Plugin Release Archive
on:
  release:
    types: [published]
jobs:
  pack-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: SPSauce Build
        uses: DosMike/SPSauce-GHAction@v1.0-alpha.1
        with:
          args: release.sauce --GITHUB_TOKEN ${{secrets.GITHUB_TOKEN}}